# Generated by Django 5.2.7 on 2025-10-15 16:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0004_rename_sales_party_sales_voucher_sales_party_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_Voucher',
            fields=[
                ('Pay_V_No', models.AutoField(primary_key=True, serialize=False)),
                ('Pay_Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Pay_Method', models.CharField(default='Cash')),
                ('Pay_Amount', models.FloatField(default=0.0)),
                ('Pay_Description', models.TextField(default='')),
                ('Pay_Party_Data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.sales_party')),
            ],
        ),
    ]
