# Generated by Django 5.2.7 on 2025-10-15 16:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0004_rename_sales_party_sales_voucher_sales_party_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt_Voucher',
            fields=[
                ('Rcpt_V_No', models.AutoField(primary_key=True, serialize=False)),
                ('Rcpt_Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Rcpt_Method', models.CharField(default='Cash')),
                ('Rcpt_Amount', models.FloatField(default=0.0)),
                ('Rcpt_Description', models.TextField(default='')),
                ('Rcpt_Party_Data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.sales_party')),
            ],
        ),
    ]
