# Generated by Django 5.2.7 on 2025-10-06 18:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase_Party',
            fields=[
                ('Purchase_Co_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Purchase_Con_GSTIN', models.CharField(default='URP', max_length=15, unique=True)),
                ('Purchase_Con_Name', models.CharField(max_length=50)),
                ('Purchase_Con_Address', models.CharField(default='N/A', max_length=200)),
                ('Purchase_Con_Pincode', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase_Voucher',
            fields=[
                ('Purchase_V_No', models.AutoField(primary_key=True, serialize=False)),
                ('Purchase_Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Purchase_Item_Name', models.CharField(default='Item', max_length=50)),
                ('Purchase_Item_Qn', models.FloatField(default=0.0)),
                ('Purchase_Item_UOM', models.CharField(default='Pcs.', max_length=3)),
                ('Purchase_Item_Rate', models.FloatField(default=0.0)),
                ('Purchase_item_To_Value', models.FloatField(default=0.0)),
                ('Purchase_GST_Per', models.FloatField(default=0.0)),
                ('Purchase_GST_Amount', models.FloatField(default=0.0)),
                ('Purchase_To_Amount', models.FloatField(default=0.0)),
                ('Purchase_Party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchase.purchase_party')),
            ],
        ),
    ]
