# Generated by Django 5.2.7 on 2025-10-06 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
        ('sales', '0003_sales_voucher_sale_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_voucher',
            name='Purchase_Party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.sales_party'),
        ),
        migrations.DeleteModel(
            name='Purchase_Party',
        ),
    ]
