# Generated by Django 5.2.7 on 2025-10-05 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sales_Voucher',
            fields=[
                ('Sales_V_No', models.AutoField(primary_key=True, serialize=False)),
                ('Sales_Party_Name', models.CharField(max_length=100)),
                ('Sale_GSTIN', models.CharField(max_length=15)),
            ],
        ),
    ]
