# Generated by Django 5.2.7 on 2025-10-05 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales_Party',
            fields=[
                ('Sales_Co_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Sales_Con_GSTIN', models.CharField(default='URP', max_length=15, unique=True)),
                ('Sales_Con_Name', models.CharField(max_length=50)),
                ('Sales_Con_Address', models.CharField(default='N/A', max_length=200)),
                ('Sales_Con_Pincode', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='sales_voucher',
            name='Sale_GSTIN',
        ),
        migrations.RemoveField(
            model_name='sales_voucher',
            name='Sales_Party_Name',
        ),
        migrations.AddField(
            model_name='sales_voucher',
            name='Sales_Party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.sales_party'),
        ),
    ]
