# Generated by Django 5.2.7 on 2025-10-05 18:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_sales_party_remove_sales_voucher_sale_gstin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales_voucher',
            name='Sale_Date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='sales_voucher',
            name='Sale_GST_Amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='sales_voucher',
            name='Sale_GST_Per',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='sales_voucher',
            name='Sale_Item_Name',
            field=models.CharField(default='Item', max_length=50),
        ),
        migrations.AddField(
            model_name='sales_voucher',
            name='Sale_Item_Qn',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='sales_voucher',
            name='Sale_Item_Rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='sales_voucher',
            name='Sale_Item_UOM',
            field=models.CharField(default='Pcs.', max_length=3),
        ),
        migrations.AddField(
            model_name='sales_voucher',
            name='Sale_To_Amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='sales_voucher',
            name='Sale_item_To_Value',
            field=models.FloatField(default=0.0),
        ),
    ]
