# Generated by Django 5.2.7 on 2025-10-12 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_sales_voucher_sale_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales_voucher',
            old_name='Sales_Party',
            new_name='Sales_Party_Data',
        ),
    ]
